# Generated by Django 4.2.10 on 2024-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
