# Generated by Django 4.2.10 on 2024-06-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_image_gallery', '0002_favourite_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'title', 'description', 'image_url', 'date', 'comment')},
        ),
    ]
